Repository CreadixGal/aeksion, pull requests merged in 2023-05, with the labels that each got.

#153 [bugfix] add validation for better control of associations avoiding null values and bereak page
  app/views/rates/_rate.html.erb
Labels: bug

#155 [hotfix] devise not login error notification translate
  config/locales/devise.es.yml
Labels: documentation, enhancement, UI/UX

#156 [hotfix] reload resource or return errors instead 500 error page for out of stock error
  app/services/stock_control.rb
Labels: bug, UI/UX

#157 [build] sql backup and restore db tasks
  Gemfile
  Gemfile.lock
  lib/tasks/database/backup.rake
  lib/tasks/database/restore.rake
Labels: documentation, feature

#158 sync
  Gemfile
  Gemfile.lock
  lib/tasks/database/backup.rake
  lib/tasks/database/restore.rake
Labels: sync

#161 [chore] rebuild migrations
  db/migrate/20221004180507_create_active_storage_tables.active_storage.rb
  db/migrate/20221017182217_create_products.rb
  db/migrate/20221017182218_create_variants.rb
  db/migrate/20221018203334_create_rates.rb
  db/migrate/20221019190020_create_movements.rb
  db/migrate/20221019191453_create_product_movements.rb
  db/migrate/20230118213050_add_state_to_movements.rb
  db/migrate/20230131203509_create_issue_trackers.rb
  db/migrate/20230201195012_change_state_for_status.rb
  db/migrate/20230201200454_default_value_status_movement.rb
  db/migrate/20230205201522_add_return_to_product_movement.rb
  db/migrate/20230207205101_add_zone_id_to_products.rb
  db/migrate/20230212183949_remove_description_from_issue_tracker.rb
  db/migrate/20230307200502_remove_price_from_rates.rb
  db/migrate/20230310195301_add_user_references_to_issue_trackers.rb
  db/migrate/20230318115213_remove_price_code_zones_from_products.rb
  db/migrate/20230401122541_remove_product_from_product_movement.rb
  db/schema.rb
Labels: documentation, enhancement

#162 [CHORE] deploy tasks
  .gitignore
  Dockerfile
  fly.toml
  lib/tasks/fly.rake
Labels: documentation

#163 [refactor] backup and restore tasks for use with volumes
  Gemfile
  Gemfile.lock
  lib/tasks/database/backup.rake
  lib/tasks/database/restore.rake
Labels: documentation, enhancement, feature

#166 Feature#pdf prawn
  Gemfile
  Gemfile.lock
  app/assets/images/icons/icon_pdf.svg
  app/controllers/movements_controller.rb
  app/views/movements/index.html.erb
  app/views/products/index.html.erb
  config/routes.rb
Labels: documentation, feature

#167 Hotfix/movement searcher across deliver riders
  app/controllers/movements_controller.rb
  app/models/delivery_rider.rb
  app/models/movement.rb
Labels: bug, enhancement
