Repository CreadixGal/aeksion, pull requests merged in 2023-03, with the labels that each got.

#119 Feaure#polimorphic price
  app/controllers/customers_controller.rb
  app/controllers/rates_controller.rb
  app/controllers/zones_controller.rb
  app/models/customer.rb
  app/models/price.rb
  app/models/product.rb
  app/models/product_movement.rb
  app/models/zone.rb
  app/views/customers/_customer.html.erb
  app/views/customers/_form.html.erb
  app/views/customers/index.html.erb
  app/views/movements/_form.html.erb
  app/views/movements/_movement.html.erb
  app/views/rates/_form.html.erb
  app/views/rates/_rate.html.erb
  app/views/zones/_form.html.erb
  app/views/zones/_zone.html.erb
  app/views/zones/index.html.erb
  db/migrate/20230203210305_create_prices.rb
  db/migrate/20230209223812_add_product_id_to_prices.rb
  db/migrate/20230307200502_remove_price_from_rates.rb
  db/schema.rb
  spec/factories.rb
  spec/models/price_spec.rb
Labels: enhancement

#122 [style] fix rubocop offenses
  app/controllers/customers_controller.rb
  app/controllers/zones_controller.rb
  app/models/customer.rb
  app/models/price.rb
  app/models/product.rb
  app/models/product_movement.rb
  app/models/zone.rb
  db/schema.rb
  spec/factories.rb
  spec/models/price_spec.rb
Labels: style

#121 Solve #114 -> quill editor for issues and comments
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/controllers/application_controller.rb
  app/controllers/issue_trackers_controller.rb
  app/javascript/controllers/quill_controller.js
  app/models/comment.rb
  app/models/issue_tracker.rb
  app/models/user.rb
  app/views/issue_trackers/_comment.html.erb
  app/views/issue_trackers/_comment_fields.html.erb
  app/views/issue_trackers/_edit_form.html.erb
  app/views/issue_trackers/_form.html.erb
  app/views/issue_trackers/_issue_tracker.html.erb
  app/views/issue_trackers/edit.html.erb
  app/views/issue_trackers/show.html.erb
  app/views/layouts/application.html.erb
  bin/bundle
  bin/dev
  bin/importmap
  bin/rake
  bin/rdebug-ide
  bin/rspec
  bin/setup
  bin/solargraph
  config/importmap.rb
  config/routes.rb
  db/migrate/20230212174758_create_comments.rb
  db/migrate/20230212183949_remove_description_from_issue_tracker.rb
  db/migrate/20230310195301_add_user_references_to_issue_trackers.rb
  db/seeds.rb
  public/coverage/coverage.svg
  spec/factories/comment.rb
  spec/factories/issue_tracker.rb
  spec/models/comment_spec.rb
  spec/models/issue_tracker_spec.rb
  spec/rails_helper.rb
  spec/requests/issue_trackers_spec.rb
Labels: feature
