Repository CreadixGal/aeksion, pull requests merged in 2023-02, with the labels that each got.

#94 Feature#states movements
  app/controllers/movements_controller.rb
  app/helpers/application_helper.rb
  app/models/movement.rb
  app/views/movements/_form.html.erb
  app/views/movements/_movement.html.erb
  app/views/movements/index.html.erb
  db/migrate/20230118213050_add_state_to_movements.rb
  db/migrate/20230201195012_change_state_for_status.rb
  db/migrate/20230201200454_default_value_status_movement.rb
  db/schema.rb
Labels: UI/UX, feature

#93 [fix] issue 65 adding filter between dates
  app/views/pages/dashboard.html.erb
Labels: bug

#97 Issue78#add products to movements
  app/assets/images/icons/calendar.svg
  app/components/modal_component.html.erb
  app/controllers/movements_controller.rb
  app/helpers/application_helper.rb
  app/javascript/controllers/flatpickr_controller.js
  app/javascript/controllers/nested_form_controller.js
  app/models/movement.rb
  app/views/movements/_edit_form.html.erb
  app/views/movements/_form.html.erb
  app/views/movements/_movement.html.erb
  app/views/movements/_product_movement_fields.html.erb
  app/views/movements/edit.html.erb
  app/views/movements/index.html.erb
  app/views/movements/new.html.erb
  app/views/pages/dashboard.html.erb
  app/views/products/_form.html.erb
  config/locales/es.yml
  public/coverage/coverage.svg
  spec/requests/movements_spec.rb
  spec/requests/pages_spec.rb
Labels: enhancement, UI/UX

#100 solve Issue74#product card
  app/assets/images/icons/image.svg
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.tailwind.css
  app/components/modal_component.html.erb
  app/views/products/_form.html.erb
  app/views/products/_product.html.erb
  app/views/products/edit.html.erb
  app/views/products/index.html.erb
  app/views/products/new.html.erb
  app/views/products/show.html.erb
  config/locales/es.yml
Labels: enhancement, UI/UX

#106 Staging
  .dockerignore
  Dockerfile
  Gemfile
  app/views/layouts/shared/_navbar.html.erb
  app/views/movements/_form.html.erb
  app/views/movements/_product_movement_fields.html.erb
  app/views/pages/dashboard.html.erb
  config/database.yml
  config/environments/staging.rb
  config/locales/es.yml
  config/storage.yml
  fly.toml
  lib/tasks/fly.rake
Labels: sync

#111 Solve #95 #90 Update movements and sync stock and amount
  app/assets/stylesheets/application.tailwind.css
  app/components/modal_component.html.erb
  app/components/tab_component.html.erb
  app/controllers/movements_controller.rb
  app/javascript/controllers/tomselect_controller.js
  app/models/movement.rb
  app/models/product_movement.rb
  app/services/stock_control.rb
  app/views/layouts/application.html.erb
  app/views/movements/_edit_form.html.erb
  app/views/movements/_form.html.erb
  app/views/movements/_movement.html.erb
  app/views/movements/_product_movement_fields.html.erb
  app/views/movements/_tabs.html.erb
  app/views/movements/edit.html.erb
  app/views/products/_form.html.erb
  bin/rails
  config/importmap.rb
  config/locales/es.yml
  config/routes.rb
  db/seeds.rb
  public/coverage/coverage.svg
  spec/requests/movements_spec.rb
Labels: bug

#109 101 request issue tracker
  app/assets/stylesheets/application.tailwind.css
  app/components/notification_status_component.html.erb
  app/components/notification_status_component.rb
  app/controllers/application_controller.rb
  app/controllers/issue_trackers_controller.rb
  app/models/issue_tracker.rb
  app/views/issue_trackers/_form.html.erb
  app/views/issue_trackers/_issue_tracker.html.erb
  app/views/issue_trackers/index.html.erb
  app/views/issue_trackers/new.html.erb
  app/views/issue_trackers/show.html.erb
  app/views/layouts/shared/_aside_menu.html.erb
  app/views/layouts/shared/_navbar.html.erb
  config/locales/es.yml
  config/routes.rb
  db/migrate/20230131203509_create_issue_trackers.rb
  db/seeds.rb
  public/coverage/coverage.svg
  spec/components/notification_status_component_spec.rb
  spec/factories/images/issue.jpg
  spec/factories/issue_tracker.rb
  spec/factories/user.rb
  spec/models/issue_tracker_spec.rb
  spec/requests/issue_trackers_spec.rb
Labels: feature

#112 sync
  app/assets/stylesheets/application.tailwind.css
  app/components/modal_component.html.erb
  app/components/notification_status_component.html.erb
  app/components/notification_status_component.rb
  app/components/tab_component.html.erb
  app/controllers/application_controller.rb
  app/controllers/issue_trackers_controller.rb
  app/controllers/movements_controller.rb
  app/javascript/controllers/tomselect_controller.js
  app/models/issue_tracker.rb
  app/models/movement.rb
  app/models/product_movement.rb
  app/services/stock_control.rb
  app/views/issue_trackers/_form.html.erb
  app/views/issue_trackers/_issue_tracker.html.erb
  app/views/issue_trackers/index.html.erb
  app/views/issue_trackers/new.html.erb
  app/views/issue_trackers/show.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/shared/_aside_menu.html.erb
  app/views/layouts/shared/_navbar.html.erb
  app/views/movements/_edit_form.html.erb
  app/views/movements/_form.html.erb
  app/views/movements/_movement.html.erb
  app/views/movements/_product_movement_fields.html.erb
  app/views/movements/_tabs.html.erb
  app/views/movements/edit.html.erb
  app/views/products/_form.html.erb
  bin/rails
  config/importmap.rb
  config/locales/es.yml
  config/routes.rb
  db/migrate/20230131203509_create_issue_trackers.rb
  db/seeds.rb
  public/coverage/coverage.svg
  spec/components/notification_status_component_spec.rb
  spec/factories/images/issue.jpg
  spec/factories/issue_tracker.rb
  spec/factories/user.rb
  spec/models/issue_tracker_spec.rb
  spec/requests/issue_trackers_spec.rb
  spec/requests/movements_spec.rb
Labels: sync

#116 resolves #104 return movement
  app/assets/images/icons/arrow-uturn-down.svg
  app/assets/stylesheets/application.tailwind.css
  app/controllers/movements_controller.rb
  app/controllers/products_controller.rb
  app/controllers/rates_controller.rb
  app/javascript/controllers/launch_modal_controller.js
  app/javascript/controllers/swal_controller.js
  app/javascript/controllers/tab_controller.js
  app/models/movement.rb
  app/models/product.rb
  app/models/product_movement.rb
  app/models/rate.rb
  app/services/stock_control.rb
  app/views/issue_trackers/index.html.erb
  app/views/layouts/shared/_aside_menu.html.erb
  app/views/movements/_movement.html.erb
  app/views/movements/_product_movement_fields.html.erb
  app/views/movements/_tabs.html.erb
  app/views/pages/configuration.html.erb
  app/views/products/_form.html.erb
  app/views/products/_product.html.erb
  app/views/rates/_form.html.erb
  app/views/rates/_rate.html.erb
  app/views/rates/_tabs.html.erb
  app/views/rates/index.html.erb
  config/locales/es.yml
  config/routes.rb
  db/migrate/20230205201522_add_return_to_product_movement.rb
  db/migrate/20230207205101_add_zone_id_to_products.rb
  spec/models/product_movement_spec.rb
  spec/requests/rates_spec.rb
Labels: bug

#120 sync
  app/assets/images/icons/arrow-uturn-down.svg
  app/assets/stylesheets/application.tailwind.css
  app/controllers/movements_controller.rb
  app/controllers/products_controller.rb
  app/controllers/rates_controller.rb
  app/javascript/controllers/launch_modal_controller.js
  app/javascript/controllers/swal_controller.js
  app/javascript/controllers/tab_controller.js
  app/models/movement.rb
  app/models/product.rb
  app/models/product_movement.rb
  app/models/rate.rb
  app/services/stock_control.rb
  app/views/issue_trackers/index.html.erb
  app/views/layouts/shared/_aside_menu.html.erb
  app/views/movements/_movement.html.erb
  app/views/movements/_product_movement_fields.html.erb
  app/views/movements/_tabs.html.erb
  app/views/pages/configuration.html.erb
  app/views/products/_form.html.erb
  app/views/products/_product.html.erb
  app/views/rates/_form.html.erb
  app/views/rates/_rate.html.erb
  app/views/rates/_tabs.html.erb
  app/views/rates/index.html.erb
  config/locales/es.yml
  config/routes.rb
  db/migrate/20230205201522_add_return_to_product_movement.rb
  db/migrate/20230207205101_add_zone_id_to_products.rb
  spec/models/product_movement_spec.rb
  spec/requests/rates_spec.rb
Labels: sync
